# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58ed5e9cd992eaae7a91f50b6da8b9bdb4375a29ebec19e5e4de5df4980d0e3299ceb0a0c2cd62b0768764347b4167d1e0a05d7bb7e19be27c6c9f3b1caeb603

test:
  secret_key_base: 8858d62ec5e349338157d68cb4af39b3902f24a8625542a0e3af06b6f79dc7800ebd4215d16f4da215a439b11d564b06fa37cbf7430ae34ff9adfd0d3b57f6ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
